---
- hosts: localhost
  name: create_aggregate
  vars_files:
    vars.yml
  tasks:
    - name: Create aggregate
      na_ontap_aggregate:
        state: present
        service_state: online
        name: "{{ aggrname }}"
        nodes: "{{ node_name_01 }}"
        disk_count: 10
        raid_size: 10
        wait_for_online: true
        hostname: "{{ netapp_hostname }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
